Reformat tab-indented files and files with 8-wide indents to 4-space indents.
google/tock-on-titan pull request #112
Opened 2019-09-20 00:08 UTC by jrvanwhy

These files ended up formatted in the way they were due to an editor misconfiguration. I will manually deconflict changes in this PR with changes from other PRs where possible.

```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
19ae5cace6608dad83f0a1b10dbd2a7787a23207
git status
On branch reformat
nothing to commit, working tree clean
```

2019-09-23 18:22 UTC, jrvanwhy commented
New version
```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
f5e465975a61a5a714dab6d94c4068aa8aca6f81
git status
On branch reformat
Your branch and 'origin/reformat' have diverged,
and have 4 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

2019-09-23 22:06 UTC, jrvanwhy commented
More rebasing: this now depends on #113 

```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
a08e20faeca76d84eea4f8332d2b04dfe3be7c3b
git status
On branch reformat
Your branch and 'origin/reformat' have diverged,
and have 3 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

2019-09-26 16:05 UTC, phil-levis-google requested changes
Overall, looks good, but also seems to have some GPIO updates woven in? Should those be removed?

2019-09-26 17:37 UTC, phil-levis-google approved these changes

2019-09-27 19:55 UTC, merged