Debug driver -- number-printing syscall driver for relocation debugging
google/tock-on-titan pull request #7
Opened 2018-12-14 20:46 UTC by jrvanwhy

This adds a "debug" driver which only relies on the `command` syscall. This driver is for Rust userspace debugging; because relocations do not currently work, the standard libtock-rs console functionality is unreliable.

It enables an application to print 1, 2, or 3 unsigned integers using a single system call. It can be removed once Rust application support and libtock-rs console support are sufficiently reliable.

2018-12-14 22:24 UTC, phil-levis-google requested changes

2018-12-14 22:24 UTC, phil-levis-google commented on golf2/src/main.rs
> +            0x80000001                    => f(Some(&DEBUG_DRIVER)),
This should at the very least be a const defined in main.rs; better yet would be to factor this out into an actual separate debug driver module.

2018-12-14 23:59 UTC, jrvanwhy commented
It appears googlebot is confused. I've filed a bug with the relevant team.

2018-12-17 19:00 UTC, phil-levis-google commented
Cool. I made one suggestion for improving the code.

2018-12-17 19:02 UTC, jrvanwhy commented
I'll let you know when it's ready for further review.

2018-12-17 19:21 UTC, jrvanwhy commented on golf2/src/main.rs
> +            0x80000001                    => f(Some(&DEBUG_DRIVER)),
I split it out, and renamed it to just Debug. Let me know if you'd rather it be DebugDriver or something else; I renamed it to make it more consistent with the other drivers but I am concerned about name conflicts.

2018-12-17 20:29 UTC, jrvanwhy commented
This is ready for further review. I'll deal with the CLA stuff when review is done (it looks like googlebot will un-fix the CLA label every time I touch this PR).

2018-12-17 20:30 UTC, phil-levis-google reviewed
If you're worried about name conflicts, then I'd suggest naming it for what it does, rather than what you're using it for. E.g., IntegerConsolePrint or something. Because, yeah, Debug is pretty overloaded.

2018-12-17 20:31 UTC, phil-levis-google approved these changes
I leave it up to you on name change.

2018-12-17 22:06 UTC, phil-levis-google commented
LGTM!

2018-12-17 22:07 UTC, phil-levis-google commented
Would you rather I merge and override the mistaken CLA gods?

2018-12-17 22:08 UTC, jrvanwhy commented
I can do the merge myself. Lets set the cla: yes label manually, rather than use GitHub's override functionality.

2018-12-17 22:19 UTC, merged