Enable read-write access to the last two flash pages.
google/tock-on-titan pull request #86
Opened 2019-06-14 01:58 UTC by jrvanwhy

Longer term, we should probably have a nicer globalsec interface. This will suffice for a single global counter, as used by the U2F app.

Commits unique to this PR:

1. Enable read-write access to the last two flash pages via globalsec.

```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
d021a80a1f57a646257ff9a32f576ff30ac37690
git status
On branch flash-globalsec
nothing to commit, working tree clean
```

2019-06-14 15:53 UTC, phil-levis-google requested changes

2019-06-14 15:53 UTC, phil-levis-google commented on golf2/src/main.rs
>          vs(0x400900cc as *mut u32, !0);
Do you want to change these earlier globalsec operations to use your consts as well? It would be better if the two sets of accesses were consistent.

2019-06-17 20:48 UTC, jrvanwhy commented on golf2/src/main.rs
>          vs(0x400900cc as *mut u32, !0);
Fine with me, done.

2019-06-17 20:48 UTC, jrvanwhy commented
Updated.

```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
1914d0724d2d0318a2efda82c42b31084c559882
git status
On branch flash-globalsec
Your branch is up to date with 'origin/flash-globalsec'.

nothing to commit, working tree clean
```

2019-06-21 14:54 UTC, phil-levis-google approved these changes

2019-06-21 17:16 UTC, merged